"""Add BookRequest model

Revision ID: 36994098a10e
Revises: a7d1bca4d21d
Create Date: 2026-08-28 08:19:22.449170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36994098a10e'
down_revision: Union[str, None] = 'a7d1bca4d21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('book_title', sa.String(length=255), nullable=False),
    sa.Column('book_author', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('offers_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_requests_book_title'), 'book_requests', ['book_title'], unique=False)
    op.create_index(op.f('ix_book_requests_requester_id'), 'book_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_requests_requester_id'), table_name='book_requests')
    op.drop_index(op.f('ix_book_requests_book_title'), table_name='book_requests')
    op.drop_table('book_requests')
    # ### end Alembic commands ###
