"""Add book requests table

Revision ID: 7801ae7cecb2
Revises: 36994098a10e
Create Date: 2026-08-28 08:23:20.634822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7801ae7cecb2'
down_revision: Union[str, None] = '36994098a10e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_requests', sa.Column('title', sa.String(length=255), nullable=False))
    op.add_column('book_requests', sa.Column('author', sa.String(length=255), nullable=False))
    op.add_column('book_requests', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('book_requests', sa.Column('owner_id', sa.UUID(), nullable=False))
    op.add_column('book_requests', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index('ix_book_requests_book_title', table_name='book_requests')
    op.drop_index('ix_book_requests_requester_id', table_name='book_requests')
    op.drop_constraint('book_requests_requester_id_fkey', 'book_requests', type_='foreignkey')
    op.create_foreign_key(None, 'book_requests', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_column('book_requests', 'note')
    op.drop_column('book_requests', 'book_author')
    op.drop_column('book_requests', 'offers_count')
    op.drop_column('book_requests', 'requester_id')
    op.drop_column('book_requests', 'book_title')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book_requests', sa.Column('book_title', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('book_requests', sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('book_requests', sa.Column('offers_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('book_requests', sa.Column('book_author', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('book_requests', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'book_requests', type_='foreignkey')
    op.create_foreign_key('book_requests_requester_id_fkey', 'book_requests', 'users', ['requester_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_book_requests_requester_id', 'book_requests', ['requester_id'], unique=False)
    op.create_index('ix_book_requests_book_title', 'book_requests', ['book_title'], unique=False)
    op.drop_column('book_requests', 'updated_at')
    op.drop_column('book_requests', 'owner_id')
    op.drop_column('book_requests', 'description')
    op.drop_column('book_requests', 'author')
    op.drop_column('book_requests', 'title')
    # ### end Alembic commands ###
